### ISSUE TITLE
iOS 8 isiPhone5 fix

### ISSUE THREAD

**Issue by tkach** [stanislaw/Environment#1]
Hi, @stanislaw ,
it seems that isiPhone5 check may return wrong results in iOS 8, because of screen bounds are now interface-oriented.
Please look at this stackoverflow discussion
http://stackoverflow.com/questions/24150359/is-uiscreen-mainscreen-bounds-size-becoming-orientation-dependent-in-ios8

**Comment by stanislaw** [comment]
@tkach, I've just announced deprecation of both my iosenv and Environment projects. They were written a long time ago in my childhood period of iOS development.

Use [RBEnvironment](https://github.com/rabovik/RSEnvironment) which is a lot better engineered solution!

I strongly recommend you proposing things like 'isJailBroken` to RSEnvironment so that you would have all the things you need there.

One more time: RSEnvironment is a lot better engineered project than my two: iosenv and Environment. So that I deprecated mine projects and now I'm migrating my current project to RSEnvironment.

**Comment by tkach** [comment]
Thank you for advice, @stanislaw 
Will migrate to RSEnvironment in my current project.
I like it!

**Comment by stanislaw** [comment]
Great! Had I implemented the third version of project other than Environment and iosenv I would write it exactly the same way as RSEnvironment is written (95% like). It is really cool exemplary Facade implementation of what we need to know about our environment :)
